# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lwb176yJ0PHCRSNovUzcOyeM1WGpciD
"""

df = pd.read_csv('adult (1).csv', sep=',', skipinitialspace=True, on_bad_lines='skip')

df.head()

df = df.dropna()

fig1 = px.histogram(df, x='age', nbins=30, title='Age Distribution')
fig1.show()

fig2 = px.bar(df, x='education', title='Education Distribution')
fig2.show()

fig3 = px.scatter(df, x='age', y='hours.per.week', color='income',
title='Age vs Working Hours')
fig3.show()

fig4 = px.pie(df, names='income', title='Income Distribution')
fig4.show()

